apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
spec:
  template:
    spec:
      containers:
        - name: neo4j
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        resources:
          requests:
            storage: 50Gi
