apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-graph-explorer

resources:
  - ../../base

patches:
  - path: patches/backend-deployment.yaml
  - path: patches/dashboard-deployment.yaml

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=development

secretGenerator:
  - name: neo4j-credentials
    literals:
      - username=neo4j
      - password=dev-password
      - auth=neo4j/dev-password
