package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/K8S-Graph-Explorer/backend/graph/generated"
	"github.com/K8S-Graph-Explorer/backend/graph/model"
)

func (r *mutationResolver) SyncCluster(ctx context.Context, namespace *string) (*model.SyncResult, error) {
	panic(fmt.Errorf("not implemented: SyncCluster - syncCluster"))
}

func (r *mutationResolver) UpsertNode(ctx context.Context, input model.NodeInput) (*model.Node, error) {
	panic(fmt.Errorf("not implemented: UpsertNode - upsertNode"))
}

func (r *mutationResolver) UpsertEdge(ctx context.Context, input model.EdgeInput) (*model.Edge, error) {
	panic(fmt.Errorf("not implemented: UpsertEdge - upsertEdge"))
}

func (r *mutationResolver) DeleteNode(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteNode - deleteNode"))
}

func (r *mutationResolver) DeleteEdge(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteEdge - deleteEdge"))
}

func (r *mutationResolver) ClearNamespace(ctx context.Context, namespace string) (bool, error) {
	panic(fmt.Errorf("not implemented: ClearNamespace - clearNamespace"))
}

func (r *queryResolver) GetTopology(ctx context.Context, filter *model.TopologyFilter) (*model.Topology, error) {
	panic(fmt.Errorf("not implemented: GetTopology - getTopology"))
}

func (r *queryResolver) GetDependencies(ctx context.Context, resourceID string, filter *model.DependencyFilter) (*model.DependencyGraph, error) {
	panic(fmt.Errorf("not implemented: GetDependencies - getDependencies"))
}

func (r *queryResolver) GetNode(ctx context.Context, id string) (*model.Node, error) {
	panic(fmt.Errorf("not implemented: GetNode - getNode"))
}

func (r *queryResolver) GetNodesByType(ctx context.Context, typeArg model.NodeType, namespace *string) ([]*model.Node, error) {
	panic(fmt.Errorf("not implemented: GetNodesByType - getNodesByType"))
}

func (r *queryResolver) SearchNodes(ctx context.Context, query string, namespace *string, limit *int) ([]*model.Node, error) {
	panic(fmt.Errorf("not implemented: SearchNodes - searchNodes"))
}

func (r *queryResolver) GetEdgesForNode(ctx context.Context, nodeID string) ([]*model.Edge, error) {
	panic(fmt.Errorf("not implemented: GetEdgesForNode - getEdgesForNode"))
}

func (r *queryResolver) FindPath(ctx context.Context, startID string, endID string, maxDepth *int) (*model.Topology, error) {
	panic(fmt.Errorf("not implemented: FindPath - findPath"))
}

func (r *subscriptionResolver) TopologyUpdated(ctx context.Context, namespace *string) (<-chan *model.TopologyEvent, error) {
	panic(fmt.Errorf("not implemented: TopologyUpdated - topologyUpdated"))
}

func (r *subscriptionResolver) NodeChanged(ctx context.Context, namespace *string) (<-chan *model.NodeEvent, error) {
	panic(fmt.Errorf("not implemented: NodeChanged - nodeChanged"))
}

func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
